- name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull origin main --rebase  # Добавляем эту строку, чтобы избежать конфликтов
          git add epg.xml
          git commit -m "Update EPG" || exit 0
          git push
